const items = {"items": [
    {
        id: 1,
        title: 'Stay sane',
        isInCloud: true,
        isCompleted: false,
        type: 'mit',
    },
    {
        id: 2,
        title: 'Prevent burnout',
        isInCloud: true,
        isCompleted: false,
        type: 'mit',
    },
    {
        id: 3,
        title: 'Eat lunch',
        isInCloud: true,
        isCompleted: false,
        type: 'todo',
    },
    {
        id: 4,
        title: 'Take breaks',
        isInCloud: true,
        isCompleted: false,
        type: 'todo',
    },
    {
        id: 5,
        title: 'Powernap',
        isInCloud: true,
        isCompleted: false,
        type: 'todo',
    },
    {
        id: 6,
        title: 'Go for a walk',
        isInCloud: true,
        isCompleted: false,
        type: 'todo',
    },
    {
        id: 7,
        title: 'Ski',
        isInCloud: true,
        isCompleted: false,
        type: 'plan',
    },
    {
        id: 8,
        title: 'Snowball fight/lumesõda',
        isInCloud: true,
        isCompleted: false,
        type: 'plan',
    },
    {
        id: 9,
        title: 'Cancel meetings after 6pm',
        isInCloud: true,
        isCompleted: false,
        type: 'plan',
    },
    {
        id: 10,
        title: 'Walking-meetings',
        isInCloud: true,
        isCompleted: false,
        type: 'plan',
    },
    {
        id: 11,
        title: 'Ask for raise',
        isInCloud: true,
        isCompleted: false,
        type: 'plan',
    },
    {
        id: 12,
        title: 'Learn estonian',
        isInCloud: true,
        isCompleted: false,
        type: 'plan',
    },
    {
        id: 13,
        title: 'Alcohol',
        isInCloud: true,
        isCompleted: false,
        type: 'reward',
    },
    {
        id: 14,
        title: 'Sauna',
        isInCloud: true,
        isCompleted: false,
        type: 'reward',
    },
    {
        id: 15,
        title: 'Order pizza',
        isInCloud: true,
        isCompleted: false,
        type: 'reward',
    },
]}

export default items;